FROM wordpress:{{wordpressTag}}

# Install PHP extensions for image processing
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

# PHP config: increase upload limits
COPY default.ini /usr/local/etc/php/conf.d/default.ini

# Apache: AllowOverride All for .htaccess support
RUN sed -i \
        -e '/<\/VirtualHost>/i\' \
        -e '        <Directory "/var/www/html">\' \
        -e '                Options Indexes FollowSymLinks MultiViews\' \
        -e '                AllowOverride All\' \
        -e '        </Directory>' \
        /etc/apache2/sites-available/000-default.conf

# SSL: install self-signed certificate
COPY cert.pem /etc/ssl/certs/cert.pem
COPY cert.key /etc/ssl/private/cert.key
RUN sed -i \
        -e "s/^\s*SSLCertificateFile\s.*/\t\tSSLCertificateFile \/etc\/ssl\/certs\/cert.pem/" \
        -e "s/^\s*SSLCertificateKeyFile\s.*/\t\tSSLCertificateKeyFile \/etc\/ssl\/private\/cert.key/" \
        /etc/apache2/sites-available/default-ssl.conf \
    && a2enmod ssl \
    && a2ensite default-ssl
